---
- name: Install epel-release package
  yum:
    name: 
     - epel-release
    state: present

- name: Install NGINX
  yum:
    name:
     - nginx
    state: present

- name: Enable NGINX service via systemd
  systemd:
    name: nginx
    enabled: yes
    masked: no
